import json
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Any

from app.schemas.report import (
    FinalAuditReport,
    ReportFindingSummary,
    ReportGenerationResponse,
    SeverityBreakdown,
    ValidationBreakdown,
)
from app.services.finding_service import list_project_findings
from app.services.reproduction_service import list_reproduction_results
from app.services.scope_validation_service import load_scope_from_project_workspace
from app.services.validation_service import list_validation_decisions


MARKDOWN_FILENAME = "final_report.md"
JSON_FILENAME = "final_report.json"
VALIDATION_STATUSES = (
    "accepted",
    "rejected",
    "duplicate",
    "needs_review",
    "out_of_scope",
    "insufficient_evidence",
    "unsafe_poc",
    "unsupported",
)
SEVERITY_LEVELS = ("Critical", "High", "Medium", "Low", "Informational")
LIMITATIONS = [
    "This report is generated by an MVP validator pipeline.",
    "Accepted findings require reproduced evidence, but human review is still recommended.",
    "Severity normalization uses deterministic heuristics.",
    "The benchmark is synthetic and not a full security guarantee.",
    "No blockchain reward or decentralized validator subnet is active yet.",
]
NOTES = [
    "Findings are grouped by validation status.",
    "Reproduction evidence is included when available.",
]


def get_reports_dir(project_workspace: Path) -> Path:
    return project_workspace / "reports"


def load_project_scope(project_workspace: Path) -> dict:
    return load_scope_from_project_workspace(project_workspace)


def load_project_metadata(project_workspace: Path) -> dict:
    for relative_path in (
        Path("metadata.json"),
        Path("project.json"),
        Path("scope") / "parsed_scope.json",
    ):
        path = project_workspace / relative_path
        if not _is_safe_child(project_workspace, path) or not path.is_file():
            continue
        loaded = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(loaded, dict):
            return loaded
    return {}


def extract_project_name(project_id: str, scope: dict, metadata: dict) -> str:
    return str(scope.get("project_name") or metadata.get("project_name") or metadata.get("name") or project_id)


def build_report_finding_summary(
    finding: Any,
    validation_decision: Any | None,
    reproduction_result: Any | None,
) -> ReportFindingSummary:
    evidence = _get_value(validation_decision, "evidence") if validation_decision is not None else None
    finding_id = _string_value(_get_value(finding, "finding_id") or _get_value(finding, "id") or "unknown")
    original_severity = _string_value(_get_value(evidence, "original_severity") or _get_value(finding, "severity"))
    normalized_severity = _string_value(_get_value(evidence, "normalized_severity"))
    reproduction_status = _string_value(
        _get_value(evidence, "reproduction_status") or _get_value(reproduction_result, "status")
    )

    return ReportFindingSummary(
        finding_id=finding_id,
        title=_string_value(_get_value(finding, "title")),
        category=_string_value(_get_value(finding, "category")),
        original_severity=original_severity,
        normalized_severity=normalized_severity,
        validation_status=_validation_status(validation_decision),
        confidence=_get_value(validation_decision, "confidence"),
        contract=_first_string(
            _get_value(finding, "contracts"),
            _get_value(finding, "contract"),
            _get_value(finding, "affected_contracts"),
        ),
        function=_first_string(
            _get_value(finding, "functions"),
            _get_value(finding, "function"),
            _get_value(finding, "affected_functions"),
        ),
        reproduction_status=reproduction_status,
        poc_file=_string_value(_get_value(reproduction_result, "poc_file")),
        test_name=_string_value(_get_value(reproduction_result, "test_name")),
        reason=_string_value(_get_value(validation_decision, "reason")),
    )


def compute_severity_breakdown(summaries: list[ReportFindingSummary]) -> SeverityBreakdown:
    counts = {severity: 0 for severity in SEVERITY_LEVELS}
    for summary in summaries:
        severity = _normalize_severity(summary.normalized_severity or summary.original_severity)
        counts[severity] += 1
    return SeverityBreakdown(**counts)


def compute_validation_breakdown(summaries: list[ReportFindingSummary]) -> ValidationBreakdown:
    counts = {status: 0 for status in VALIDATION_STATUSES}
    for summary in summaries:
        status = summary.validation_status if summary.validation_status in counts else "needs_review"
        counts[status] += 1
    return ValidationBreakdown(**counts)


def group_summaries_by_validation_status(
    summaries: list[ReportFindingSummary],
) -> dict[str, list[ReportFindingSummary]]:
    groups = {status: [] for status in VALIDATION_STATUSES}
    for summary in summaries:
        status = summary.validation_status if summary.validation_status in groups else "needs_review"
        groups[status].append(summary)
    return groups


def build_final_audit_report(
    project_id: str,
    project_workspace: Path,
) -> FinalAuditReport:
    findings = list_project_findings(project_workspace)
    decisions = {decision.finding_id: decision for decision in list_validation_decisions(project_workspace)}
    reproductions = {result.finding_id: result for result in list_reproduction_results(project_workspace)}
    summaries = [
        build_report_finding_summary(
            finding,
            decisions.get(finding.finding_id),
            reproductions.get(finding.finding_id),
        )
        for finding in findings
    ]
    groups = group_summaries_by_validation_status(summaries)
    scope = load_project_scope(project_workspace)
    metadata = load_project_metadata(project_workspace)

    return FinalAuditReport(
        project_id=project_id,
        project_name=extract_project_name(project_id, scope, metadata),
        generated_at=datetime.now(timezone.utc),
        scope=scope,
        total_findings=len(summaries),
        severity_breakdown=compute_severity_breakdown(summaries),
        validation_breakdown=compute_validation_breakdown(summaries),
        accepted_findings=groups["accepted"],
        rejected_findings=groups["rejected"],
        duplicate_findings=groups["duplicate"],
        needs_review_findings=groups["needs_review"],
        out_of_scope_findings=groups["out_of_scope"],
        insufficient_evidence_findings=groups["insufficient_evidence"],
        unsafe_poc_findings=groups["unsafe_poc"],
        unsupported_findings=groups["unsupported"],
        limitations=LIMITATIONS.copy(),
        notes=NOTES.copy(),
    )


def render_markdown_report(report: FinalAuditReport) -> str:
    lines = [
        "# ProofGuard Audit Report",
        "",
        "## Project",
        "",
        f"- Project ID: {report.project_id}",
        f"- Project name: {report.project_name or report.project_id}",
        f"- Generated at: {report.generated_at.isoformat()}",
        "",
        "## Scope",
        "",
    ]
    lines.extend(_render_scope(report.scope))
    lines.extend(
        [
            "",
            "## Executive Summary",
            "",
            f"- Total findings: {report.total_findings}",
            f"- Accepted: {report.validation_breakdown.accepted}",
            f"- Rejected: {report.validation_breakdown.rejected}",
            f"- Duplicates: {report.validation_breakdown.duplicate}",
            f"- Needs review: {report.validation_breakdown.needs_review}",
            f"- Out of scope: {report.validation_breakdown.out_of_scope}",
            f"- Insufficient evidence: {report.validation_breakdown.insufficient_evidence}",
            f"- Unsafe PoC: {report.validation_breakdown.unsafe_poc}",
            f"- Unsupported: {report.validation_breakdown.unsupported}",
            "",
            "## Severity Breakdown",
            "",
            "| Severity      | Count |",
            "| ------------- | ----- |",
            f"| Critical      | {report.severity_breakdown.Critical}     |",
            f"| High          | {report.severity_breakdown.High}     |",
            f"| Medium        | {report.severity_breakdown.Medium}     |",
            f"| Low           | {report.severity_breakdown.Low}     |",
            f"| Informational | {report.severity_breakdown.Informational}     |",
            "",
            "## Validation Breakdown",
            "",
            "| Status                | Count |",
            "| --------------------- | ----- |",
            f"| accepted              | {report.validation_breakdown.accepted}     |",
            f"| rejected              | {report.validation_breakdown.rejected}     |",
            f"| duplicate             | {report.validation_breakdown.duplicate}     |",
            f"| needs_review          | {report.validation_breakdown.needs_review}     |",
            f"| out_of_scope          | {report.validation_breakdown.out_of_scope}     |",
            f"| insufficient_evidence | {report.validation_breakdown.insufficient_evidence}     |",
            f"| unsafe_poc            | {report.validation_breakdown.unsafe_poc}     |",
            f"| unsupported           | {report.validation_breakdown.unsupported}     |",
            "",
            "## Accepted Findings",
            "",
        ]
    )
    lines.extend(_render_findings(report.accepted_findings))
    lines.extend(["", "## Findings Requiring Review", ""])
    lines.extend(_render_findings(report.needs_review_findings))
    lines.extend(["", "## Rejected / Insufficient Evidence Findings", ""])
    lines.extend(_render_findings([*report.rejected_findings, *report.insufficient_evidence_findings]))
    lines.extend(["", "## Duplicate Findings", ""])
    lines.extend(_render_findings(report.duplicate_findings))
    lines.extend(["", "## Out of Scope Findings", ""])
    lines.extend(_render_findings(report.out_of_scope_findings))
    lines.extend(["", "## Unsafe or Unsupported Findings", ""])
    lines.extend(_render_findings([*report.unsafe_poc_findings, *report.unsupported_findings]))
    lines.extend(["", "## Limitations", ""])
    lines.extend(_render_list(report.limitations))
    lines.extend(["", "## Notes", ""])
    lines.extend(_render_list(report.notes))
    return "\n".join(lines).rstrip() + "\n"


def save_final_audit_report(
    project_id: str,
    project_workspace: Path,
) -> ReportGenerationResponse:
    report = build_final_audit_report(project_id, project_workspace)
    markdown = render_markdown_report(report)
    reports_dir = get_reports_dir(project_workspace)
    reports_dir.mkdir(parents=True, exist_ok=True)
    json_path = reports_dir / JSON_FILENAME
    markdown_path = reports_dir / MARKDOWN_FILENAME
    json_path.write_text(
        json.dumps(report.model_dump(mode="json"), indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    markdown_path.write_text(markdown, encoding="utf-8")
    return ReportGenerationResponse(
        project_id=project_id,
        markdown_path=f"reports/{MARKDOWN_FILENAME}",
        json_path=f"reports/{JSON_FILENAME}",
        total_findings=report.total_findings,
        accepted_count=report.validation_breakdown.accepted,
        message="Final audit report generated.",
    )


def load_final_audit_report_json(
    project_workspace: Path,
) -> FinalAuditReport | None:
    path = get_reports_dir(project_workspace) / JSON_FILENAME
    if not path.exists():
        return None
    return FinalAuditReport.model_validate_json(path.read_text(encoding="utf-8"))


def load_final_audit_report_markdown(
    project_workspace: Path,
) -> str | None:
    path = get_reports_dir(project_workspace) / MARKDOWN_FILENAME
    if not path.exists():
        return None
    return path.read_text(encoding="utf-8")


def _render_scope(scope: dict) -> list[str]:
    if not scope:
        return ["No scope information found."]
    return [
        f"- contracts_in_scope: {_format_scope_list(scope.get('contracts_in_scope'))}",
        f"- contracts_out_of_scope: {_format_scope_list(scope.get('contracts_out_of_scope'))}",
        f"- attack_categories: {_format_scope_list(scope.get('attack_categories'))}",
        f"- assets_at_risk: {_format_scope_list(scope.get('assets_at_risk'))}",
    ]


def _render_findings(summaries: list[ReportFindingSummary]) -> list[str]:
    if not summaries:
        return ["None."]
    lines: list[str] = []
    for summary in summaries:
        title = summary.title or "Untitled finding"
        lines.extend(
            [
                f"### {summary.finding_id}: {title}",
                "",
                f"- Severity: {summary.normalized_severity or summary.original_severity or 'Unknown'}",
                f"- Category: {summary.category or 'Unknown'}",
                f"- Contract: {summary.contract or 'Unknown'}",
                f"- Function: {summary.function or 'Unknown'}",
                f"- Confidence: {_format_confidence(summary.confidence)}",
                f"- Reproduction status: {summary.reproduction_status or 'Unknown'}",
                f"- PoC file: {summary.poc_file or 'None'}",
                f"- Test name: {summary.test_name or 'None'}",
                f"- Reason: {summary.reason or 'None'}",
                "",
            ]
        )
    return lines[:-1]


def _render_list(values: list[str]) -> list[str]:
    if not values:
        return ["None."]
    return [f"- {value}" for value in values]


def _format_scope_list(value: Any) -> str:
    if isinstance(value, list):
        return ", ".join(str(item) for item in value) if value else "None"
    if value:
        return str(value)
    return "None"


def _format_confidence(value: float | None) -> str:
    if value is None:
        return "Unknown"
    return f"{value:.2f}"


def _normalize_severity(value: str | None) -> str:
    if not value:
        return "Informational"
    normalized = value.strip().lower()
    mapping = {
        "critical": "Critical",
        "crit": "Critical",
        "high": "High",
        "medium": "Medium",
        "med": "Medium",
        "low": "Low",
        "informational": "Informational",
        "info": "Informational",
        "informative": "Informational",
    }
    return mapping.get(normalized, "Informational")


def _validation_status(validation_decision: Any | None) -> str:
    status = _string_value(_get_value(validation_decision, "status"))
    return status if status in VALIDATION_STATUSES else "needs_review"


def _first_string(*values: Any) -> str | None:
    for value in values:
        if isinstance(value, list):
            for item in value:
                if item is not None:
                    return _string_value(item)
        elif value is not None:
            return _string_value(value)
    return None


def _get_value(source: Any, key: str) -> Any:
    if source is None:
        return None
    if isinstance(source, dict):
        return source.get(key)
    return getattr(source, key, None)


def _string_value(value: Any) -> str | None:
    if value is None:
        return None
    if isinstance(value, Enum):
        return str(value.value)
    return str(value)


def _is_safe_child(project_workspace: Path, path: Path) -> bool:
    workspace = project_workspace.resolve(strict=False)
    resolved = path.resolve(strict=False)
    try:
        resolved.relative_to(workspace)
    except ValueError:
        return False
    return True
